[package]
name = "hsa-sys"
version = "0.1.3"
edition = "2021"

[dependencies]
utilities = { path = "../utilities" }

[dev-dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.71.1"

[features]
default = ["rocm_6_2_2"]
rocm_6_2_2 = []
